insert into location values (1,"Agrigento");
insert into location values (2,"Alessandria");
insert into location values (3,"Ancona");
insert into location values (4,"Aost");
 insert into location values (5,"Arezzo");
 -- insert into location values (6,"Ascoli Piceno");
 insert into location values (7,"Asti");
 insert into location values (8,"Avellino");
 insert into location values (9,"Bari");
 -- insert into location values (10,"Barletta-Adriana-Trani");
 insert into location values (11,"Belluno");
 insert into location values (12,"Benevento");
 insert into location values (13,"Bergamo");
 insert into location values (14,"Biella");
 insert into location values (15,"Bologna");
 insert into location values (16,"Bolzano");
 insert into location values (17,"Brescia");
 insert into location values (18,"Brindisi");
 insert into location values (19,"Cagliari");
 insert into location values (20,"Caltanissetta");
 -- insert into location values (21,"Carbonia-Iglesias");
 insert into location values (22,"Campobasso");
 insert into location values (23,"Caserta");
 insert into location values (24,"Catania");
 insert into location values (25,"Catanzaro");
 insert into location values (26,"Chieti");
 insert into location values (27,"Como");
 insert into location values (28,"Cosenza");
 insert into location values (29,"Cremona");
 insert into location values (30,"Crotone");
 insert into location values (31,"Cuneo");
 insert into location values (32,"Enna");
 insert into location values (33,"Fermo");
 insert into location values (34,"Ferrara");
 insert into location values (35,"Firenze");
 insert into location values (36,"Foggia");
 -- insert into location values (37,"Forli-Cesena");
 insert into location values (38,"Frosinone");
insert into location values (39,"Genova");
 insert into location values (40,"Gorizia");
insert into location values (41,"Grosseto");
 insert into location values (42,"Imperia");
 insert into location values (43,"Isernia");
 -- insert into location values (44,"La Spezia");
 -- insert into location values (45,"L' Acquila");
 insert into location values (46,"Latina");
 insert into location values (47,"Lecce");
 insert into location values (48,"Lecco");
 insert into location values (49,"Lvorno");
 insert into location values (50,"Lodi");
 insert into location values (51,"Lucca");
 insert into location values (52,"Macerta");
 insert into location values (53,"Mantova");
 -- insert into location values (54,"Massa-Carrara");
 insert into location values (55,"Matera");
 insert into location values (56,"Messina");
 insert into location values (57,"Milano");
 insert into location values (58,"Modena");
 insert into location values (59,"Monza");
 insert into location values (60,"Napoli");
 insert into location values (61,"Nuoro");
 insert into location values (62,"Novara");
 -- insert into location values (63,"Olbia-Tempio");
 insert into location values (64,"Oristano");
 insert into location values (65,"Padova");
 insert into location values (66,"Palermo");
 insert into location values (67,"Parma");
 insert into location values (68,"Pavia");
insert into location values (69,"Perugia");
 -- insert into location values (70,"Pesaro e Urbino");
 insert into location values (71,"Pescara");
 insert into location values (72,"Piacenza");
 insert into location values (73,"Pisa");
 insert into location values (74,"Pistoia");
 insert into location values (75,"Pordenone");
 insert into location values (76,"Potenza");
 insert into location values (77,"Prato");
 insert into location values (78,"Ragusa");
 insert into location values (79,"Ravenna");
 -- insert into location values (80,"Reggio Emilia");
 -- insert into location values (81,"Reggio Calabria");
insert into location values (82,"Rieti");
 insert into location values (83,"Rimini");
 insert into location values (84,"Roma");
insert into location values (85,"Rovigo");
 insert into location values (86,"Salerno");
 -- insert into location values (87,"Medio Campidano");
 insert into location values (88,"Sassari");
 insert into location values (89,"Savona");
 insert into location values (90,"Siena");
 insert into location values (91,"Siracusa");
 insert into location values (92,"Sondrio");
 insert into location values (93,"Taranto");
 insert into location values (94,"Teramo");
 insert into location values (95,"Terni");
 insert into location values (96,"Torino");
 insert into location values (97,"Olgiastra");
 insert into location values (98,"Trapani");
 insert into location values (99,"Trento");
 insert into location values (100,"Trieste");
 insert into location values (101,"Udine");
 insert into location values (102,"Varese");
 insert into location values (103,"Venezia");
 -- insert into location values (104,"Verbano-Cusio-Ossola");
 insert into location values (105,"Vercelli");
 insert into location values (106,"Verona");
 -- insert into location values (107,"Vibo-Valentia");
 insert into location values (108,"Vicanza");
insert into location values (109,"Viterbo");